/** Static LaTeX knowledge used for completion. */

export interface CommandSpec {
  /** Without the leading backslash. */
  name: string
  /** Monaco snippet body, without the backslash. */
  snippet?: string
  detail?: string
  documentation?: string
}

export interface EnvironmentSpec {
  name: string
  /** Body inserted between \begin and \end. */
  body?: string
  detail?: string
}

export const LATEX_COMMANDS: CommandSpec[] = [
  // Structure
  { name: 'documentclass', snippet: 'documentclass{${1:article}}', detail: 'Document class' },
  { name: 'usepackage', snippet: 'usepackage{${1:package}}', detail: 'Load a package' },
  { name: 'begin', snippet: 'begin{${1:environment}}\n\t$0\n\\end{${1:environment}}', detail: 'Open an environment' },
  { name: 'end', snippet: 'end{${1:environment}}', detail: 'Close an environment' },
  { name: 'part', snippet: 'part{${1:title}}', detail: 'Part heading' },
  { name: 'chapter', snippet: 'chapter{${1:title}}', detail: 'Chapter heading' },
  { name: 'section', snippet: 'section{${1:title}}', detail: 'Section heading' },
  { name: 'subsection', snippet: 'subsection{${1:title}}', detail: 'Subsection heading' },
  { name: 'subsubsection', snippet: 'subsubsection{${1:title}}', detail: 'Subsubsection heading' },
  { name: 'paragraph', snippet: 'paragraph{${1:title}}', detail: 'Paragraph heading' },
  { name: 'subparagraph', snippet: 'subparagraph{${1:title}}' },
  { name: 'appendix', detail: 'Start the appendices' },
  { name: 'frontmatter', detail: 'Book front matter' },
  { name: 'mainmatter', detail: 'Book main matter' },
  { name: 'backmatter', detail: 'Book back matter' },

  // Title & meta
  { name: 'title', snippet: 'title{${1:title}}' },
  { name: 'author', snippet: 'author{${1:name}}' },
  { name: 'date', snippet: 'date{${1:\\today}}' },
  { name: 'maketitle', detail: 'Typeset the title block' },
  { name: 'today', detail: "Today's date" },
  { name: 'tableofcontents', detail: 'Insert the table of contents' },
  { name: 'listoffigures' },
  { name: 'listoftables' },

  // Cross references
  { name: 'label', snippet: 'label{${1:key}}', detail: 'Define a reference target' },
  { name: 'ref', snippet: 'ref{${1:key}}', detail: 'Reference a label' },
  { name: 'eqref', snippet: 'eqref{${1:key}}', detail: 'Reference an equation' },
  { name: 'pageref', snippet: 'pageref{${1:key}}', detail: 'Reference a page number' },
  { name: 'autoref', snippet: 'autoref{${1:key}}', detail: 'Reference with its type (hyperref)' },
  { name: 'nameref', snippet: 'nameref{${1:key}}' },
  { name: 'cref', snippet: 'cref{${1:key}}', detail: 'Clever reference (cleveref)' },
  { name: 'Cref', snippet: 'Cref{${1:key}}', detail: 'Capitalised clever reference' },
  { name: 'footnote', snippet: 'footnote{${1:text}}' },
  { name: 'marginpar', snippet: 'marginpar{${1:text}}' },

  // Citations
  { name: 'cite', snippet: 'cite{${1:key}}', detail: 'Cite a bibliography entry' },
  { name: 'citep', snippet: 'citep{${1:key}}', detail: 'Parenthetical citation (natbib)' },
  { name: 'citet', snippet: 'citet{${1:key}}', detail: 'Textual citation (natbib)' },
  { name: 'citeauthor', snippet: 'citeauthor{${1:key}}' },
  { name: 'citeyear', snippet: 'citeyear{${1:key}}' },
  { name: 'parencite', snippet: 'parencite{${1:key}}', detail: 'Parenthetical citation (biblatex)' },
  { name: 'textcite', snippet: 'textcite{${1:key}}', detail: 'Textual citation (biblatex)' },
  { name: 'autocite', snippet: 'autocite{${1:key}}' },
  { name: 'nocite', snippet: 'nocite{${1:key}}' },
  { name: 'bibliography', snippet: 'bibliography{${1:references}}' },
  { name: 'bibliographystyle', snippet: 'bibliographystyle{${1:plain}}' },
  { name: 'addbibresource', snippet: 'addbibresource{${1:references.bib}}', detail: 'biblatex bibliography' },
  { name: 'printbibliography', detail: 'Print the bibliography (biblatex)' },

  // Files
  { name: 'input', snippet: 'input{${1:file}}', detail: 'Insert another file' },
  { name: 'include', snippet: 'include{${1:file}}', detail: 'Insert a file on a new page' },
  { name: 'includeonly', snippet: 'includeonly{${1:file}}' },
  { name: 'graphicspath', snippet: 'graphicspath{{${1:images/}}}' },
  { name: 'includegraphics', snippet: 'includegraphics[width=${1:0.8\\textwidth}]{${2:file}}', detail: 'Insert an image' },

  // Text formatting
  { name: 'textbf', snippet: 'textbf{${1:text}}', detail: 'Bold' },
  { name: 'textit', snippet: 'textit{${1:text}}', detail: 'Italic' },
  { name: 'texttt', snippet: 'texttt{${1:text}}', detail: 'Monospace' },
  { name: 'textsc', snippet: 'textsc{${1:text}}', detail: 'Small capitals' },
  { name: 'textsf', snippet: 'textsf{${1:text}}', detail: 'Sans serif' },
  { name: 'textrm', snippet: 'textrm{${1:text}}' },
  { name: 'underline', snippet: 'underline{${1:text}}' },
  { name: 'emph', snippet: 'emph{${1:text}}', detail: 'Emphasis' },
  { name: 'textsuperscript', snippet: 'textsuperscript{${1:text}}' },
  { name: 'textsubscript', snippet: 'textsubscript{${1:text}}' },
  { name: 'verb', snippet: 'verb|${1:text}|', detail: 'Inline verbatim' },
  { name: 'url', snippet: 'url{${1:https://}}' },
  { name: 'href', snippet: 'href{${1:https://}}{${2:text}}' },
  { name: 'texorpdfstring', snippet: 'texorpdfstring{${1:tex}}{${2:pdf}}' },

  // Sizes
  { name: 'tiny' },
  { name: 'scriptsize' },
  { name: 'footnotesize' },
  { name: 'small' },
  { name: 'normalsize' },
  { name: 'large' },
  { name: 'Large' },
  { name: 'LARGE' },
  { name: 'huge' },
  { name: 'Huge' },

  // Spacing & layout
  { name: 'newpage' },
  { name: 'clearpage' },
  { name: 'cleardoublepage' },
  { name: 'pagebreak' },
  { name: 'linebreak' },
  { name: 'newline' },
  { name: 'noindent' },
  { name: 'indent' },
  { name: 'centering' },
  { name: 'raggedright' },
  { name: 'raggedleft' },
  { name: 'vspace', snippet: 'vspace{${1:1cm}}' },
  { name: 'hspace', snippet: 'hspace{${1:1cm}}' },
  { name: 'vfill' },
  { name: 'hfill' },
  { name: 'smallskip' },
  { name: 'medskip' },
  { name: 'bigskip' },
  { name: 'hrule' },
  { name: 'rule', snippet: 'rule{${1:\\linewidth}}{${2:0.4pt}}' },

  // Boxes and figures
  { name: 'caption', snippet: 'caption{${1:caption}}' },
  { name: 'captionof', snippet: 'captionof{${1:figure}}{${2:caption}}' },
  { name: 'subfloat', snippet: 'subfloat[${1:caption}]{${2:content}}' },
  { name: 'fbox', snippet: 'fbox{${1:text}}' },
  { name: 'mbox', snippet: 'mbox{${1:text}}' },
  { name: 'parbox', snippet: 'parbox{${1:width}}{${2:text}}' },
  { name: 'makebox', snippet: 'makebox[${1:width}]{${2:text}}' },
  { name: 'raisebox', snippet: 'raisebox{${1:lift}}{${2:text}}' },

  // Tables
  { name: 'hline' },
  { name: 'cline', snippet: 'cline{${1:1-2}}' },
  { name: 'toprule', detail: 'booktabs' },
  { name: 'midrule', detail: 'booktabs' },
  { name: 'bottomrule', detail: 'booktabs' },
  { name: 'cmidrule', snippet: 'cmidrule(lr){${1:1-2}}', detail: 'booktabs' },
  { name: 'multicolumn', snippet: 'multicolumn{${1:2}}{${2:c}}{${3:text}}' },
  { name: 'multirow', snippet: 'multirow{${1:2}}{${2:*}}{${3:text}}', detail: 'multirow' },

  // Lists
  { name: 'item', snippet: 'item ${1:text}' },

  // Maths
  { name: 'frac', snippet: 'frac{${1:a}}{${2:b}}' },
  { name: 'dfrac', snippet: 'dfrac{${1:a}}{${2:b}}' },
  { name: 'tfrac', snippet: 'tfrac{${1:a}}{${2:b}}' },
  { name: 'sqrt', snippet: 'sqrt{${1:x}}' },
  { name: 'sum', snippet: 'sum_{${1:i=1}}^{${2:n}}' },
  { name: 'prod', snippet: 'prod_{${1:i=1}}^{${2:n}}' },
  { name: 'int', snippet: 'int_{${1:a}}^{${2:b}}' },
  { name: 'iint' },
  { name: 'oint' },
  { name: 'lim', snippet: 'lim_{${1:x \\to 0}}' },
  { name: 'infty' },
  { name: 'partial' },
  { name: 'nabla' },
  { name: 'cdot' },
  { name: 'cdots' },
  { name: 'ldots' },
  { name: 'vdots' },
  { name: 'ddots' },
  { name: 'times' },
  { name: 'div' },
  { name: 'pm' },
  { name: 'mp' },
  { name: 'leq' },
  { name: 'geq' },
  { name: 'neq' },
  { name: 'approx' },
  { name: 'equiv' },
  { name: 'sim' },
  { name: 'simeq' },
  { name: 'propto' },
  { name: 'in' },
  { name: 'notin' },
  { name: 'subset' },
  { name: 'subseteq' },
  { name: 'supset' },
  { name: 'cup' },
  { name: 'cap' },
  { name: 'setminus' },
  { name: 'emptyset' },
  { name: 'forall' },
  { name: 'exists' },
  { name: 'neg' },
  { name: 'land' },
  { name: 'lor' },
  { name: 'implies' },
  { name: 'iff' },
  { name: 'to' },
  { name: 'mapsto' },
  { name: 'rightarrow' },
  { name: 'leftarrow' },
  { name: 'Rightarrow' },
  { name: 'Leftarrow' },
  { name: 'leftrightarrow' },
  { name: 'Leftrightarrow' },
  { name: 'langle' },
  { name: 'rangle' },
  { name: 'lfloor' },
  { name: 'rfloor' },
  { name: 'lceil' },
  { name: 'rceil' },
  { name: 'left', snippet: 'left${1:(}' },
  { name: 'right', snippet: 'right${1:)}' },
  { name: 'mathbb', snippet: 'mathbb{${1:R}}' },
  { name: 'mathcal', snippet: 'mathcal{${1:F}}' },
  { name: 'mathbf', snippet: 'mathbf{${1:x}}' },
  { name: 'mathrm', snippet: 'mathrm{${1:d}}' },
  { name: 'mathit', snippet: 'mathit{${1:x}}' },
  { name: 'mathfrak', snippet: 'mathfrak{${1:g}}' },
  { name: 'boldsymbol', snippet: 'boldsymbol{${1:x}}' },
  { name: 'operatorname', snippet: 'operatorname{${1:name}}' },
  { name: 'DeclareMathOperator', snippet: 'DeclareMathOperator{\\\\${1:name}}{${2:text}}' },
  { name: 'text', snippet: 'text{${1:text}}' },
  { name: 'quad' },
  { name: 'qquad' },
  { name: 'overline', snippet: 'overline{${1:x}}' },
  { name: 'hat', snippet: 'hat{${1:x}}' },
  { name: 'bar', snippet: 'bar{${1:x}}' },
  { name: 'tilde', snippet: 'tilde{${1:x}}' },
  { name: 'vec', snippet: 'vec{${1:x}}' },
  { name: 'dot', snippet: 'dot{${1:x}}' },
  { name: 'binom', snippet: 'binom{${1:n}}{${2:k}}' },
  { name: 'sin' },
  { name: 'cos' },
  { name: 'tan' },
  { name: 'log' },
  { name: 'ln' },
  { name: 'exp' },
  { name: 'max' },
  { name: 'min' },
  { name: 'arg' },
  { name: 'det' },
  { name: 'dim' },
  { name: 'ker' },

  // Greek
  { name: 'alpha' },
  { name: 'beta' },
  { name: 'gamma' },
  { name: 'delta' },
  { name: 'epsilon' },
  { name: 'varepsilon' },
  { name: 'zeta' },
  { name: 'eta' },
  { name: 'theta' },
  { name: 'vartheta' },
  { name: 'iota' },
  { name: 'kappa' },
  { name: 'lambda' },
  { name: 'mu' },
  { name: 'nu' },
  { name: 'xi' },
  { name: 'pi' },
  { name: 'rho' },
  { name: 'sigma' },
  { name: 'tau' },
  { name: 'upsilon' },
  { name: 'phi' },
  { name: 'varphi' },
  { name: 'chi' },
  { name: 'psi' },
  { name: 'omega' },
  { name: 'Gamma' },
  { name: 'Delta' },
  { name: 'Theta' },
  { name: 'Lambda' },
  { name: 'Xi' },
  { name: 'Pi' },
  { name: 'Sigma' },
  { name: 'Upsilon' },
  { name: 'Phi' },
  { name: 'Psi' },
  { name: 'Omega' },

  // Definitions
  { name: 'newcommand', snippet: 'newcommand{\\\\${1:name}}[${2:0}]{${3:definition}}' },
  { name: 'renewcommand', snippet: 'renewcommand{\\\\${1:name}}{${2:definition}}' },
  { name: 'newenvironment', snippet: 'newenvironment{${1:name}}{${2:begin}}{${3:end}}' },
  { name: 'newtheorem', snippet: 'newtheorem{${1:theorem}}{${2:Theorem}}' },
  { name: 'setlength', snippet: 'setlength{\\\\${1:parskip}}{${2:1em}}' },
  { name: 'addtolength', snippet: 'addtolength{\\\\${1:parskip}}{${2:1em}}' },
  { name: 'def', snippet: 'def\\\\${1:name}{${2:definition}}' }
]

export const LATEX_ENVIRONMENTS: EnvironmentSpec[] = [
  { name: 'document', detail: 'The document body' },
  { name: 'abstract', detail: 'Summary at the start of a paper' },
  { name: 'itemize', body: '\t\\item $0', detail: 'Bulleted list' },
  { name: 'enumerate', body: '\t\\item $0', detail: 'Numbered list' },
  { name: 'description', body: '\t\\item[${1:term}] $0', detail: 'Description list' },
  { name: 'figure', body: '\t\\centering\n\t\\includegraphics[width=${1:0.8\\textwidth}]{${2:file}}\n\t\\caption{${3:caption}}\n\t\\label{fig:${4:key}}', detail: 'Floating figure' },
  { name: 'figure*', detail: 'Full-width figure in two-column layouts' },
  { name: 'table', body: '\t\\centering\n\t\\begin{tabular}{${1:lcr}}\n\t\t$0\n\t\\end{tabular}\n\t\\caption{${2:caption}}\n\t\\label{tab:${3:key}}', detail: 'Floating table' },
  { name: 'table*', detail: 'Full-width table in two-column layouts' },
  { name: 'tabular', body: '\t$0', detail: 'Table body' },
  { name: 'tabularx', detail: 'Table with stretchable columns' },
  { name: 'array', detail: 'Maths matrix-like array' },
  { name: 'equation', body: '\t$0', detail: 'Numbered equation' },
  { name: 'equation*', body: '\t$0', detail: 'Unnumbered equation' },
  { name: 'align', body: '\t$0', detail: 'Aligned equations, numbered' },
  { name: 'align*', body: '\t$0', detail: 'Aligned equations, unnumbered' },
  { name: 'gather', body: '\t$0' },
  { name: 'multline', body: '\t$0' },
  { name: 'split', body: '\t$0' },
  { name: 'cases', body: '\t$0', detail: 'Case distinction' },
  { name: 'matrix', body: '\t$0' },
  { name: 'pmatrix', body: '\t$0', detail: 'Matrix with parentheses' },
  { name: 'bmatrix', body: '\t$0', detail: 'Matrix with brackets' },
  { name: 'vmatrix', body: '\t$0', detail: 'Determinant' },
  { name: 'center', body: '\t$0', detail: 'Centred block' },
  { name: 'flushleft', body: '\t$0' },
  { name: 'flushright', body: '\t$0' },
  { name: 'quote', body: '\t$0' },
  { name: 'quotation', body: '\t$0' },
  { name: 'verse', body: '\t$0' },
  { name: 'verbatim', body: '$0', detail: 'Literal text' },
  { name: 'lstlisting', body: '$0', detail: 'Source code (listings)' },
  { name: 'minted', body: '$0', detail: 'Source code (minted)' },
  { name: 'minipage', body: '\t$0', detail: 'Box of a given width' },
  { name: 'thebibliography', body: '\t\\bibitem{${1:key}} $0' },
  { name: 'theorem', body: '\t$0' },
  { name: 'lemma', body: '\t$0' },
  { name: 'proof', body: '\t$0' },
  { name: 'definition', body: '\t$0' },
  { name: 'corollary', body: '\t$0' },
  { name: 'remark', body: '\t$0' },
  { name: 'example', body: '\t$0' },
  { name: 'frame', body: '\t$0', detail: 'Beamer slide' },
  { name: 'columns', body: '\t$0', detail: 'Beamer columns' },
  { name: 'column', body: '\t$0' },
  { name: 'block', body: '\t$0', detail: 'Beamer highlighted block' },
  { name: 'tikzpicture', body: '\t$0', detail: 'TikZ drawing' },
  { name: 'axis', body: '\t$0', detail: 'pgfplots axis' },
  { name: 'letter', body: '\t$0' },
  { name: 'titlepage', body: '\t$0' },
  { name: 'appendices', body: '\t$0' },
  { name: 'subequations', body: '\t$0' }
]

export const LATEX_PACKAGES: { name: string; detail: string }[] = [
  { name: 'inputenc', detail: 'Input encoding, use [utf8]' },
  { name: 'fontenc', detail: 'Font encoding, use [T1]' },
  { name: 'babel', detail: 'Language and hyphenation rules' },
  { name: 'geometry', detail: 'Page margins and paper size' },
  { name: 'graphicx', detail: 'Include images' },
  { name: 'amsmath', detail: 'Extended maths environments' },
  { name: 'amssymb', detail: 'Extra maths symbols' },
  { name: 'amsthm', detail: 'Theorem environments' },
  { name: 'mathtools', detail: 'Fixes and extensions for amsmath' },
  { name: 'hyperref', detail: 'Clickable links and PDF metadata' },
  { name: 'cleveref', detail: 'Smarter cross references' },
  { name: 'booktabs', detail: 'Professional table rules' },
  { name: 'tabularx', detail: 'Tables with stretchable columns' },
  { name: 'longtable', detail: 'Tables spanning several pages' },
  { name: 'multirow', detail: 'Cells spanning several rows' },
  { name: 'array', detail: 'Extended column specifications' },
  { name: 'caption', detail: 'Caption formatting' },
  { name: 'subcaption', detail: 'Sub-figures and sub-captions' },
  { name: 'float', detail: 'Precise float placement with [H]' },
  { name: 'wrapfig', detail: 'Text wrapped around figures' },
  { name: 'xcolor', detail: 'Colour support' },
  { name: 'tikz', detail: 'Vector drawing' },
  { name: 'pgfplots', detail: 'Plots from data' },
  { name: 'listings', detail: 'Source code listings' },
  { name: 'minted', detail: 'Syntax-highlighted code, needs Pygments' },
  { name: 'algorithm2e', detail: 'Algorithms and pseudocode' },
  { name: 'algorithmic', detail: 'Pseudocode' },
  { name: 'natbib', detail: 'Author-year citations' },
  { name: 'biblatex', detail: 'Modern bibliography handling' },
  { name: 'csquotes', detail: 'Context-sensitive quotation marks' },
  { name: 'setspace', detail: 'Line spacing' },
  { name: 'parskip', detail: 'Blank line between paragraphs' },
  { name: 'enumitem', detail: 'Customisable lists' },
  { name: 'fancyhdr', detail: 'Headers and footers' },
  { name: 'titlesec', detail: 'Heading formatting' },
  { name: 'tocloft', detail: 'Table of contents formatting' },
  { name: 'lmodern', detail: 'Latin Modern fonts' },
  { name: 'microtype', detail: 'Micro-typographic refinements' },
  { name: 'siunitx', detail: 'Units and number formatting' },
  { name: 'physics', detail: 'Shorthand for physics notation' },
  { name: 'bm', detail: 'Bold maths symbols' },
  { name: 'url', detail: 'Line-breakable URLs' },
  { name: 'lipsum', detail: 'Placeholder text' },
  { name: 'todonotes', detail: 'Margin to-do notes' },
  { name: 'appendix', detail: 'Appendix handling' },
  { name: 'glossaries', detail: 'Glossaries and acronyms' },
  { name: 'makeidx', detail: 'Index generation' },
  { name: 'fontspec', detail: 'System fonts, XeLaTeX and LuaLaTeX only' },
  { name: 'unicode-math', detail: 'Unicode maths fonts' },
  { name: 'subfiles', detail: 'Compile chapters on their own' },
  { name: 'standalone', detail: 'Standalone figures' },
  { name: 'pdfpages', detail: 'Include pages of other PDFs' },
  { name: 'rotating', detail: 'Rotated figures and tables' },
  { name: 'multicol', detail: 'Multi-column text' },
  { name: 'ulem', detail: 'Underlining and strikeout' },
  { name: 'soul', detail: 'Letterspacing and highlighting' }
]

export const DOCUMENT_CLASSES: { name: string; detail: string }[] = [
  { name: 'article', detail: 'Papers and short documents' },
  { name: 'report', detail: 'Longer documents with chapters' },
  { name: 'book', detail: 'Books, two-sided by default' },
  { name: 'beamer', detail: 'Presentations' },
  { name: 'letter', detail: 'Letters' },
  { name: 'memoir', detail: 'Highly configurable book class' },
  { name: 'scrartcl', detail: 'KOMA-Script article' },
  { name: 'scrreprt', detail: 'KOMA-Script report' },
  { name: 'scrbook', detail: 'KOMA-Script book' },
  { name: 'standalone', detail: 'Single figure or fragment' },
  { name: 'IEEEtran', detail: 'IEEE conference and journal papers' },
  { name: 'acmart', detail: 'ACM publications' },
  { name: 'revtex4-2', detail: 'APS and AIP journals' }
]

/** Commands whose first argument is a label reference. */
export const REF_COMMANDS = new Set([
  'ref',
  'eqref',
  'pageref',
  'autoref',
  'nameref',
  'cref',
  'Cref',
  'crefrange',
  'vref',
  'labelcref'
])

/** Commands whose first argument is a citation key list. */
export const CITE_COMMANDS = new Set([
  'cite',
  'citep',
  'citet',
  'citealp',
  'citealt',
  'citeauthor',
  'citeyear',
  'citeyearpar',
  'nocite',
  'parencite',
  'textcite',
  'autocite',
  'footcite',
  'fullcite',
  'supercite',
  'Textcite',
  'Parencite',
  'Autocite'
])

/** Commands whose argument names a project file. */
export const FILE_COMMANDS = new Set([
  'input',
  'include',
  'includeonly',
  'subfile',
  'includegraphics',
  'bibliography',
  'addbibresource',
  'lstinputlisting',
  'inputminted',
  'includepdf'
])
