/*
 * Puts a launcher in front of the Linux binary.
 *
 * Chromium sandboxes its renderer either through an unprivileged user
 * namespace or through a small chrome-sandbox helper that must be owned by
 * root with mode 4755. Ubuntu 24.04 denies unprivileged user namespaces to
 * programs that have no AppArmor profile granting them, and an AppImage is a
 * read-only nosuid mount that cannot carry a setuid file, so on those machines
 * Chromium aborts before a single line of this application runs:
 *
 *   FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was
 *   found, but is not configured correctly.
 *
 * There is no fixing that from inside the process, because the process is dead
 * before it starts, so the executable becomes a short script instead.
 *
 * The script does not try to predict the answer. Asking the kernel through
 * some other program, `unshare` for instance, produces a confident lie:
 * AppArmor decides this per executable, and Ubuntu ships a profile that lets
 * `unshare` create a namespace while denying the same thing to an unprofiled
 * AppImage. So the launcher simply starts the application and watches. Chromium
 * aborts on SIGTRAP within a fraction of a second, before the application has
 * opened a window, taken the single-instance lock or touched a file, which
 * makes starting it a second time without the sandbox safe. A crash later in a
 * session looks nothing like that and is left alone.
 */
const fs = require('node:fs')
const path = require('node:path')

const LAUNCHER = `#!/bin/bash
# Generated by scripts/after-pack.cjs. See that file for why this exists.
here="$(dirname "$(readlink -f "$0")")"
real="$here/@BINARY@.bin"

# Installed from the .deb the helper is setuid root, so the sandbox always
# works and there is nothing to watch for.
if [ -u "$here/chrome-sandbox" ]; then
  exec "$real" "$@"
fi

started=$SECONDS
"$real" "$@"
status=$?

# Killed by a signal, within seconds of starting, having drawn nothing: that is
# Chromium giving up on the sandbox rather than the application failing.
if [ "$status" -ge 128 ] && [ $((SECONDS - started)) -le 5 ]; then
  echo "sheaf: this system does not allow this build to sandbox itself, so it is" >&2
  echo "sheaf: starting again with the sandbox off. The .deb package keeps the" >&2
  echo "sheaf: sandbox; see the project README for how to keep it here too." >&2
  exec "$real" --no-sandbox "$@"
fi

exit $status
`

exports.default = async function afterPack(context) {
  if (context.electronPlatformName !== 'linux') return

  const binary = context.packager.executableName
  const target = path.join(context.appOutDir, binary)
  const moved = `${target}.bin`

  // The hook can run more than once for a multi-target build.
  if (fs.existsSync(moved)) return
  if (!fs.existsSync(target)) {
    throw new Error(`afterPack: expected to find ${target}`)
  }

  fs.renameSync(target, moved)
  fs.writeFileSync(target, LAUNCHER.replace('@BINARY@', binary), { mode: 0o755 })
  console.log(`  • sandbox launcher installed in front of ${binary}`)
}
